#!/bin/bash

PKGS=(
    android-tools
    android-udev
    archlinux-appstream-data
    base-devel
    breeze-cursors
    brotli
    cabextract
    caja
    cpio
    crow-translate
    engrampa
    fish
    firefox
    flatpak
    galculator
    gamemode
    gedit
    gedit-plugins
    geoclue
    gnome-keyring
    gst-libav
    gst-plugins-bad
    gst-plugins-ugly
    gvfs
    gvfs-mtp
    kdeconnect
    lib32-gamemode
    lib32-mangohud
    lib32-nvidia-utils
    libappindicator
    libayatana-appindicator
    libreoffice-fresh
    lightdm
    lightdm-gtk-greeter
    lightdm-gtk-greeter-settings
    linux-zen-headers
    liquidctl
    mangohud
    nano
    network-manager-applet
    nvidia-open-dkms
    nvidia-settings
    nvidia-utils
    onnxruntime-cpu
    os-prober
    p7zip
    papirus-icon-theme
    parole
    pavucontrol
    pkgfile
    python
    qbittorrent
    qt5-base
    qt6-tools
    rpm-tools
    sshfs
    steam
    telegram-desktop
    tesseract-data-eng
    tesseract-data-rus
    tesseract-data-ukr
    thunar-archive-plugin
    thunar-media-tags-plugin
    unace
    unrar
    unzip
    viewnior
    vivaldi
    vivaldi-ffmpeg-codecs
    webkit2gtk-4.1
    webkitgtk-6.0
    xcape
    xclip
    xdg-desktop-portal
    xdg-user-dirs-gtk
    xfce4
    xfce4-pulseaudio-plugin
    xfce4-screensaver
    xfce4-screenshooter
    xfce4-taskmanager
    xfce4-whiskermenu-plugin
    xfce4-xkb-plugin
    xorg
    xorg-fonts-misc
)

pacman -S --noconfirm --needed "${PKGS[@]}"
