#!/bin/bash

PKGS=(
    7zip
    android-tools
    android-udev
    archlinux-appstream-data
    base-devel
    binutils
    breeze-cursors
    bzip3
    cabextract
    cava
    cdrtools
    celluloid
    cpio
    crow-translate
    cups-pk-helper
    dpkg
    fastfetch
    file-roller
    firefox
    fish
    flatpak
    gamemode
    gamescope
    geoclue
    gnome-boxes
    gnome-calculator
    gnome-keyring
    gnome-text-editor
    grsync
    gvfs
    gvfs-mtp
    hyprland-guiutils
    i2c-tools
    kdeconnect
    kimageformats
    lhasa
    lib32-gamemode
    lib32-mangohud
    lib32-nvidia-utils
    libappindicator
    libreoffice-fresh
    linux-zen-headers
    liquidctl
    loupe
    lrzip
    mangohud
    nano
    nautilus
    ntfs-3g
    ntfsprogs
    nvidia-open-dkms
    nvidia-settings
    nvidia-utils
    onnxruntime-cpu
    os-prober
    p7zip
    papirus-icon-theme
    power-profiles-daemon
    pkgfile
    python
    qbittorrent
    qt5-base
    qt6-tools
    rpmextract
    squashfs-tools
    sshfs
    steam
    telegram-desktop
    tesseract-data-eng
    tesseract-data-rus
    tesseract-data-ukr
    unace
    unrar
    unzip
    webkit2gtk-4.1
    webkitgtk-6.0
    wl-clipboard
    wtype
    xdg-desktop-portal
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    #xdg-desktop-portal-hyprland
    xdg-user-dirs-gtk
    xorg-fonts-misc
    zip
)

pacman -S --noconfirm --needed "${PKGS[@]}"
